CREATE TABLE IF NOT EXISTS CLIENTES (
  documento INT NOT NULL,
  nombre VARCHAR(50) NOT NULL,
  apellido VARCHAR(50) NOT NULL,
  telefono VARCHAR(20) NOT NULL,
  direccion VARCHAR(150) NOT NULL,
  correo VARCHAR(150) NOT NULL,
  metodopago VARCHAR(50) NOT NULL
);
